Fixes SimulinkCheckParser fingerprinting issue
jenkinsci/analysis-model pull request #1121
Opened 2024-12-25 13:07 UTC by Jay-oao

This pull request fixes the issue with the SimulinkCheckParser where model file extensions (e.g., .slx, .mdl , etc) were missing in the filenames passed to the IssueBuilder. Previously, the parser extracted only the model name without its extension, causing fingerprinting errors during processing of Simulink Check Tool reports.  (https://issues.jenkins.io/browse/JENKINS-72838)
### Testing done
Created a freestyle Project and parsed a static html report with the model present in the workspace.

<img width="945" alt="fingerprint" src="https://github.com/user-attachments/assets/a719aaa5-be96-4a4a-978c-169cd226bd16" />

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-12-27 13:26 UTC, uhafner requested changes

2024-12-27 13:26 UTC, uhafner commented on src/main/java/edu/hm/hafner/analysis/parser/SimulinkCheckParser.java
> +            var system = modelNameElement.text();
`modelNameElement ` might  be `null` so this needs to wrapped in an `if` (and the alternative is using the existing value?).

2024-12-27 13:26 UTC, uhafner commented on src/main/java/edu/hm/hafner/analysis/parser/SimulinkCheckParser.java
> +            var system = modelNameElement.text();
Can you also add an assertion in the corresponding test for the new value?

2025-01-02 09:08 UTC, Jay-oao commented on src/main/java/edu/hm/hafner/analysis/parser/SimulinkCheckParser.java
> +            var system = modelNameElement.text();
> `modelNameElement ` might be `null` so this needs to wrapped in an `if` (and the alternative is using the existing value?).

Using the existing value as an alternative is bound to log the `Can't create fingerprints for some files`. Maybe throwing a ParsingException would be more appropriate here ?

2025-01-03 16:32 UTC, uhafner commented on src/main/java/edu/hm/hafner/analysis/parser/SimulinkCheckParser.java
> +            var system = modelNameElement.text();
Throwing a parsing exception is also fine (if the user of this parser has the option to create the file with the correct `modelNameElement`).

2025-01-04 20:00 UTC, uhafner approved these changes

2025-01-04 20:00 UTC, merged

2025-01-04 20:00 UTC, uhafner commented
Thanks for the PR!