Added dockerlinter parser analysis
jenkinsci/analysis-model pull request #537
Opened 2020-11-24 14:57 UTC by iamabhishek-dubey

Signed-off-by: iamabhishek-dubey <abhishekbhardwaj510@gmail.com>

2020-11-25 05:35 UTC, iamabhishek-dubey commented
This Jenkins build is not failed because of my code changes, Please review :D

2020-11-26 06:59 UTC, iamabhishek-dubey commented
I will fix this codecov alerts

2020-11-26 07:26 UTC, iamabhishek-dubey commented
Fixed codecov warning, the job is failed because of the JNLP connection issue

2020-11-26 11:00 UTC, uhafner requested changes

2020-11-26 11:00 UTC, uhafner commented on src/test/java/edu/hm/hafner/analysis/parser/OTDockerLintParserTest.java
> +    void unusualInput() {
What exactly is the difference to the other test (ot-docker-linter.json)?

2020-11-26 12:52 UTC, iamabhishek-dubey commented
Please review @uhafner

2020-11-26 21:14 UTC, uhafner approved these changes

2020-11-26 21:14 UTC, merged

2020-11-26 21:14 UTC, uhafner commented
Thanks!