Adding support for cargo clippy output
jenkinsci/analysis-model pull request #895
Opened 2023-02-21 15:03 UTC by madelaney

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

This change will add support for parsing `cargo clippy` output from the rust tool chain, as well as a test for the current `cargo clippy` output.

2023-02-27 10:02 UTC, uhafner requested changes

2023-02-28 14:06 UTC, madelaney commented on src/main/java/edu/hm/hafner/analysis/parser/cargo/CargoClippyParser.java
> +                    throw new IllegalArgumentException("Parser cannot parse file line or column", ex);
Sure, I'll just ignore/swallow the exception.

2023-02-28 14:11 UTC, madelaney commented on src/main/java/edu/hm/hafner/analysis/parser/cargo/CargoClippyParser.java
> +         */
Sorry, Java is not my primary language so I was just trying to follow what I could find.

2023-02-28 14:12 UTC, madelaney commented on src/main/java/edu/hm/hafner/analysis/parser/cargo/CargoClippyParser.java
> +        final Pattern expression = Pattern.compile("^.+help:(?<message>.+)");
Thanks, I'll add that.

2023-03-18 11:58 UTC, madelaney commented on src/main/java/edu/hm/hafner/analysis/parser/cargo/CargoClippyParser.java
> +        public String getRecommendation() {
I wasn't sure how that would be formatted in the Jenkins UI, but I can try to see what I can do.

2023-03-19 12:32 UTC, madelaney commented on src/main/java/edu/hm/hafner/analysis/parser/cargo/CargoClippyParser.java
> +        public String getRecommendation() {
I believe I have resolved this.

2023-03-19 21:34 UTC, uhafner requested changes

2023-03-19 21:34 UTC, uhafner commented on .project
> +	<filteredResources>
Please revert unrelated changes. 

(I need to remove them from the project in a separate PR)

2023-03-19 21:34 UTC, uhafner commented on .settings/org.eclipse.core.resources.prefs
> +encoding//src/main/resources=UTF-8
revert

2023-03-19 21:34 UTC, uhafner commented on .settings/org.eclipse.jdt.core.prefs
revert

2023-03-19 21:34 UTC, uhafner commented on src/main/java/edu/hm/hafner/analysis/parser/CargoCheckParser.java
> +import java.util.Optional;
Revert, there is no real change?

2023-03-19 21:34 UTC, uhafner commented on src/main/java/edu/hm/hafner/analysis/parser/cargo/CargoClippyParser.java
> +                    fileInformation.setLine(Integer.parseInt(fileInfoMatcher.group("line")));
Use `IntegerParser` then you can remove the try-catch

2023-03-19 21:34 UTC, uhafner commented on src/main/java/edu/hm/hafner/analysis/parser/cargo/Utils.java
> +    public static int countChar(final String str, final char c) {
This method already exists: `StringUtils.countMatches`

2023-03-19 21:34 UTC, uhafner commented on src/test/java/edu/hm/hafner/analysis/parser/cargo/UtilsTest.java
Not needed, `StringUtils.countMatches`

2023-03-19 21:34 UTC, uhafner commented on src/test/java/edu/hm/hafner/analysis/parser/cargo/CargoClippyParserTest.java
> +                .hasColumnStart(53);
Can you check the new description for one example as well?

2023-05-12 09:38 UTC, merged