Add parser for CCES (CrossCore Embedded Studio)
jenkinsci/analysis-model pull request #937
Opened 2023-07-31 14:35 UTC by arthur-devialet

Add support for parsing compiler logs generated by CrossCore Embedded Studio.

### Notes

- Implementation inspired from `Gcc4CompilerParser.java` and `EmbeddedEngineerParser.java`
- Compiler errors are not parsed, only warnings. Could be improved in a second stage

### Testing done

- Added relatively extensive tests in `CrossCoreEmbeddedStudioParserTest.java` 

### See also

- https://github.com/jenkinsci/warnings-ng-plugin/pull/1566

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

#### Extra:
- [x] Update SUPPORTED-FORMATS.md.
Not clear to me how to  _"run `main` method of `ParserRegistry`"_. Where is the binary? (Note that my java level is extremely low)

2023-07-31 16:19 UTC, arthur-devialet commented on src/main/java/edu/hm/hafner/analysis/parser/CrossCoreEmbeddedStudioParser.java
> +    private static final long serialVersionUID = 5490211629355204910L;
`5490211629355204910L` was copied from `Gcc4CompilerParser.java`.

How to generate it otherwise?

2023-08-01 09:20 UTC, uhafner requested changes
Looks good! Thanks for your PR.

Can you please regenerate the SUPPORTED_FORMATS file by running `mvn verify`?

2023-08-01 14:14 UTC, uhafner approved these changes
Thanks for your PR!

2023-08-01 14:14 UTC, uhafner commented on src/main/java/edu/hm/hafner/analysis/registry/CrossCoreEmbeddedStudioDescriptor.java
> +    private static final String ID = "crosscore-embedded-studio";
This ID `"crosscore-embedded-studio"` will be used in the UI later on in the warnings plugin. Is it ok for you or do you want to shorten it to something like `crosscore`?

2023-08-01 15:42 UTC, merged